services:
  app:
    image: sammyalade/register:latest
    restart: on-failure
    environment:
      spring.datasource.url: ${DATABASE_URL}
      spring.datasource.username: ${DATABASE_USERNAME}
      spring.datasource.password: ${DATABASE_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "9090:9090"
    mem_limit: 128m
    cpus: "1.0"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 128m
        reservations:
          cpus: "0.5"
          memory: 128m

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 128m
    cpus: "0.5"

volumes:
  postgres_data:
